config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :movies
  root 'movies#index'
  patch '/movies/:id/rating', to:'movies#set_movie_rating'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :movie, optional: true
  has_many :movies, :dependent => :destroy
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :category, optional: true
  has_many :categories
  has_many :ratings, :dependent => :destroy
  validates :title, presence: true
  validates :text, presence: true
  validates :url, presence: true
  validates :category_id, presence: true

  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :movie, optional: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[  edit update destroy show set_movie_rating]
  before_action :set_access_for_admin_page, only: %i[ new edit]
  before_action :set_user, only: %i[ show ]

  def index
    @category = Category.find_by(id: params[:id])
    @categories = [Category.new(name: 'All categories')] + Category.all
    @movies = (@category&.movies || Movie.all).paginate(page: params[:page], per_page: 6)

  end

  def show
    @rating_total = @movie.ratings.average(:rating)
  end

  def new
    @movie = Movie.new
  end

  def edit
  end

  def create
    @movie = Movie.new(movie_params)
    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def set_movie_rating
    rating = @movie.ratings.find_or_create_by!(user_id: current_user.id)
    rating.rating = params[:rating]
    rating.save
    @rating_total = @movie.ratings.average(:rating)
    respond_to do |format|
      format.js { render partial: 'layouts/rating' }
    end
  end

  private

  def set_access_for_admin_page
    if current_user
      if current_user.email != "my@mail.com"
        redirect_to movies_url
      end
    end
  end

  def set_user
    if current_user
      if current_user.email == "my@mail.com"
        @user = true
      else
        @user = false
      end
    end
  end

  def set_movie
    @movie = Movie.friendly.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :text, :category_id, :url)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def after_sign_up_path_for(resource)
    movies_path
  end

  def after_sign_in_path_for(resource)
    movies_path
  end

  def after_sign_out_path_for(resource)
    movies_path
  end

end

app/controllers/users/devise_controller.rb
class Users::DeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/_rating.js.erb
document.getElementById('rating').innerHTML = '<h3> Rating: <%= @rating_total.ceil(1) %>/10 </h3>'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movie</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag "styles.css" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>
      <ul>
        <% movie.errors.each do |error| %>
          <%= error.full_message %><br>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text, class: "form-control" %>
  </div>
  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url, class: "form-control" %>
  </div>
  <div>
    <br>
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<br>
<div id="<%= dom_id movie %>">
  <p>
    <%= image_tag(movie.url, :width => 160, :height => 240) %>
  </p>
</div>

app/views/movies/_movie_show.html.erb
<div id="<%= dom_id movie %>">
  <p>
    <%= image_tag(movie.url, :width => 300, :height => 460) %>
    <strong>Title:</strong>
    <%= movie.title %>
  </p>
  <p>
    <strong>Text:</strong>
    <%= movie.text %>
  </p>
</div>

app/views/movies/_movies.html.erb
<% if @movies.any? %>
  <div id="movies">
    <div class="row">
      <% @movies.each do |movie| %>
        <div class="col-auto">
          <%= render movie %>
          <%= link_to movie.title, movie, class: 'link_to' %><br>
          <div id="stars" class="form-stars-multi" data-controller="ratings" data-ratings-my-value="<%= movie_path movie %>/rating" data-action="input->ratings#greet">
            <div class="ratings_multi <% movie.title %>">
              <% 10.downto(1) do |i| %>
                <input type="radio" name="ratings_multi" value="<%= i %>" id="<%= i %> <%=movie.title%>">
                <label for="<%= i %> <%=movie.title%>">☆</label>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <h3>The current category does not include films</h3>
<% end %>

app/views/movies/_navbar.html.erb
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">MoviesCenter</a>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#"> </a>
      </li>
      <%= form_with url: movies_path, method: :get do |form| %>
        <li class="nav-item">
        <li class="nav-item">
          <a class="nav-link">
            <%= form.collection_select :id, @categories, :id, :name, { selected: params[:id] }, id: "movie_category_id" %>
            <%= form.submit 'Switch', class: "btn btn-primary" %>
      <% end %>
      </a>
      </li>
      <li class="nav-item">
        <% if user_signed_in? %>
          <a class="nav-link ">
            <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %></a>
        <% else %>
          <a class="nav-link  position_add">
            <%= link_to 'Log in', new_user_session_path, class: "btn btn-success login" %>
        <% end %>
        </a>
      </li>
    </ul>
    <% if current_user && current_user.email == "my@mail.com" %>
      <form class="form-inline my-2 my-lg-0">
        <%= link_to '+ Add Movie', { controller: "movies", action: :new }, class: "btn btn-warning my-2 my-sm-0" %>
      </form>
    <% end %>
  </div>
</nav>

app/views/movies/_rating.html.erb
<div id="rating">
  <h3>Rating:
    <% if @rating_total.nil? %>
      0/10
    <% else %>
      <%= @rating_total.ceil(1) %>/10
    <% end %></h3>
</div>
<% if current_user %>
  <div id="stars" class="form-stars" data-controller="rating" data-action="input->rating#greet">
    <div class="rating">
      <input id="movie_path" value="<%= movie_path @movie %>/rating" hidden>
      <% 10.downto(1) do |i| %>
        <input type="radio" name="rating" value="<%= i %>" id=<%= i %>>
        <label for=<%= i %>>☆</label>
      <% end %>
    </div>
  </div>
<% else %>
  <h4> Login to rate  <%= link_to 'Log in', new_user_session_path, class: "btn btn-success" %> </h4>
<% end %>

app/views/movies/edit.html.erb
<div class="container">
  <h1>Editing movie</h1>
  <%= render "form", movie: @movie %>
  <%= link_to "Show this movie", @movie %> |
  <%= link_to "Back to movies", movies_path %>
</div>
<br>

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <%= render 'navbar' %>
  <%= render 'movies' %>
  <%= will_paginate @movies, class: "paginaton" %>
</div>

app/views/movies/new.html.erb
<div class='container'>
  <h1>New movie</h1>
  <%= render "form", movie: @movie %>
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>
  <div id="<%= dom_id @movie %>">
    <%= image_tag(@movie.url, :width => 300, :height => 400) %>
    <p>
      <strong>Title:</strong>
      <%= @movie.title %><br>
      <strong>Description:</strong>
      <%= @movie.text %>
    </p>
    <%= render 'rating' %>
    <%= link_to "Back to movies", movies_path %>
    <% if @user %>
      <div>
        <%= link_to "Edit this movie", edit_movie_path(@movie) %>
        <%= button_to "Destroy this movie", @movie, method: :delete, class: "btn btn-danger" %>
      </div>
    <% end %>
  </div>
</div>